add check for qmake for friendlier install failure closes #17 (#21)
* add check for qmake for friendlier install failure closes #17

* update README & fix logic in setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -6,9 +6,29 @@
 # Exit if any subcommand fails
 set -e
 
+# Check for existence & version of QMake, otherwise bundle install fails on capybara-webkit in an unfriendly way
+qmake_check() {
+	which qmake > /dev/null
+
+	if [[ $? -eq 1 ]]; then
+		echo "You need to install QMake to be able to install the capybara-webkit gem. See https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit"
+		exit 1
+	fi
+
+	q_version=$(qmake --version)
+
+	if [[ "$q_version" != *"Qt version 5"* ]]; then
+		echo $q_version
+		echo "It looks like your version of QMake is out of date!\nPlease make sure QMake is built with at least Qt 5. See https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit"
+		exit 1
+	fi
+
+	false # forces bundle install to run if the bundle check exit status == 1 but qmake exists
+}
+
 # Set up Ruby dependencies via Bundler
 gem install bundler --conservative
-bundle check || bundle install
+(bundle check || qmake_check) || bundle install
 
 # Set up database and add any development seed data
 bin/rake dev:prime
